server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ken1989/ConfigData
          username: dingkebuaa@163.com
          password: IBM_Ding&19890207
          timeout: 5
          default-label: master